mob-cap-per-apocalypse: 200

messages:
  command:
    help: "&cUsage: /zombieapocalypse <start|stop|end|saveexamples>"
    apocalypse-required: "&cYou must provide an apocalypse as an argument!"
    no-permission: "&cYou do not have permission to run this command!"
    invalid-apocalypse: "&c'%0' is not a valid apocalypse!"

    no-apocalypses-started: "&cNo apocalypses were started"
    starting-apocalypses: "&aStarting apocalypses..."
    started-apocalypse: "&aStarted apocalypse '&e%0&a'"
    done-starting-apocalyses: "&aDone starting apocalypses!"
 
    no-apocalypses-stopped: "&cNo apocalypses were stopped"
    stopping-apocalypses: "&aStopping apocalypses..."
    stopped-apocalypse-naturally: "&aStopped apocalypse '&e%0&a' naturally"
    stopped-apocalypse-forcefully: "&aStopped apocalypse '&e%0&a' forcefully"
    done-stopping-apocalyses: "&aDone stopping apocalypses!"
    
    saved-examples: "&bSaved examples successfully!"
  notifications:
    started-apocalypse: "&c&lThe sky darkens and you hear sounds coming from the ground..."
    completed-apocalypse: "&aYou have successfully survived the onslaught!" 
    not-enough-players: "&cThe hordes leave due to lack of competition..."   
    win-stuff: "&bYou have won glorious loot!"
    lost-stuff: "&cYou have failed to defeat the onslaught."
    died: "&cYou have fallen victim to the monsters..."
    no-tp: "&cA mysterious force prevents you from teleporting..."
    escaped: "&bYou have escaped from the advancing horde!"