main: io.github.bananapuncher714.zombieapocalypse.ZombieApocalypse
name: ZombieApocalypse
version: 1.0
author: BananaPuncher714
description: Adds cool stuff
softdepend:
- "MVdWPlaceholderAPI"
- "PlaceholderAPI"
- "Cartographer"
commands:
  zombieapocalypse:
    description: displays information about the Zombie Apocalypse plugin
    aliases:
    - "za"