main: io.github.bananapuncher714.zombieapocalypse.ZombieApocalypse
name: ZombieApocalypse
version: 42.0
author: BananaPuncher714
description: Davy Jones be lookin fer me doubloons
softdepend:
- "MVdWPlaceholderAPI"
- "PlaceholderAPI"
- "Cartographer"
commands:
  zombieapocalypse:
    description: What be ye' lookin' here for? This be MY booty!
    aliases:
    - "za"